import { afterEach, describe, expect, test } from "bun:test";
import { mkdirSync, mkdtempSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  GENERATED_ADAPTER_PATHS,
  generateAdapters,
  generateAgentAdapter,
  diagnoseScopes,
  inspectConflicts,
  isGeneratedAdapter,
  loadNorms,
  normApplies,
  parseNorm,
  readStarterPack,
  serializeNorm,
  serializeStarterPack,
  STARTER_PACK,
} from "../src/index";

const roots: string[] = [];

afterEach(() => {
  for (const root of roots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe("norms core", () => {
  test("loads, sorts, and scopes local norms", () => {
    const root = fixture();
    writeFileSync(
      join(root, ".norms/norms/typescript.md"),
      serializeNorm("coding.typescript", ["src/**/*.ts"], "# TypeScript\n\nUse strict types."),
    );
    const norms = loadNorms(root);
    expect(norms.map(({ id }) => id)).toEqual(["coding.typescript"]);
    expect(normApplies(norms[0], "src/index.ts")).toBe(true);
    expect(normApplies(norms[0], "README.md")).toBe(false);
  });

  test("rejects duplicate ids", () => {
    const root = fixture();
    writeFileSync(join(root, ".norms/norms/a.md"), serializeNorm("coding.typescript", ["**/*"], "Use TypeScript."));
    writeFileSync(join(root, ".norms/norms/b.md"), serializeNorm("coding.typescript", ["**/*"], "Use JavaScript."));
    expect(() => loadNorms(root)).toThrow("Conflicting norm id");
  });

  test("combines provenance for identical ids", () => {
    const root = fixture();
    const norm = serializeNorm("coding.typescript", ["**/*"], "Use TypeScript.");
    writeFileSync(join(root, ".norms/norms/a.md"), norm);
    writeFileSync(join(root, ".norms/norms/b.md"), norm);
    expect(loadNorms(root)).toHaveLength(1);
  });

  test("generates a deterministic adapter", () => {
    const norm = parseNorm(
      serializeNorm("docs.short", ["**/*.md"], "Keep docs short."),
      "short.md",
      "repository",
    );
    const first = generateAgentAdapter([norm]);
    expect(generateAgentAdapter([norm])).toBe(first);
    expect(first).toContain("docs.short");
    expect(first).toContain("Do not edit");
    expect(first).toContain("provenance, not priority");
    expect(first).toContain("report the conflict");
    expect(first).not.toMatch(/VISION\.md|TypeScript|Bun|React|Ink|Yoga/);

    const adapters = generateAdapters([norm]);
    expect(adapters.map(({ path }) => path)).toEqual([...GENERATED_ADAPTER_PATHS]);
    expect(adapters.every(({ content }) => content.includes("docs.short"))).toBe(true);
    expect(adapters.find(({ path }) => path.endsWith(".mdc"))?.content).toStartWith("---\ndescription: Active repository norms\nglobs:\nalwaysApply: true\n---");
    expect(adapters.every(({ content }) => isGeneratedAdapter(content))).toBe(true);
    expect(isGeneratedAdapter("---\ndescription: Human rule\n---\n\n# Keep\n\n<!-- Generated by Norms. Do not edit; run `norms sync`. -->")).toBe(false);
  });

  test("diagnoses scopes and declared conflicts", () => {
    const backend = parseNorm(
      serializeNorm("backend.errors", ["src/**"], "Use typed errors.", ["company.errors"]),
      "backend.md",
      "repository",
    );
    const company = parseNorm(serializeNorm("company.errors", ["src/**/*.ts"], "Use error codes."), "company.md", "shared");
    const docs = parseNorm(serializeNorm("docs.short", ["docs/**"], "Keep docs short."), "docs.md", "repository");
    const norms = [backend, company, docs];
    const diagnostics = diagnoseScopes(norms, "src/index.ts");
    expect(diagnostics.find(({ id }) => id === "backend.errors")).toMatchObject({ applies: true, matchedScopes: ["src/**"] });
    expect(diagnostics.find(({ id }) => id === "docs.short")).toMatchObject({ applies: false, unmatchedScopes: ["docs/**"] });
    expect(inspectConflicts(norms, "src/index.ts").conflicts[0]).toMatchObject({
      ids: ["backend.errors", "company.errors"],
      declaredBy: ["backend.errors"],
    });
    expect(inspectConflicts(norms, "docs/readme.md").conflicts).toHaveLength(0);
  });

  test("reports missing conflict targets", () => {
    const norm = parseNorm(serializeNorm("backend.errors", ["**/*"], "Use typed errors.", ["missing.errors"]), "backend.md", "repository");
    expect(inspectConflicts([norm]).missingTargets).toEqual([{ normId: "backend.errors", targetId: "missing.errors" }]);
  });

  test("packages every canonical meta-norm", () => {
    const files = readdirSync(join(import.meta.dir, "../../../.norms/norms/meta")).sort();
    expect(STARTER_PACK.norms.map(({ path }) => path.replace("meta/", ""))).toEqual(files);
    expect(readStarterPack(serializeStarterPack())).toEqual(STARTER_PACK);
  });
});

function fixture(): string {
  const root = mkdtempSync(join(tmpdir(), "norms-core-"));
  roots.push(root);
  mkdirSync(join(root, ".git"));
  mkdirSync(join(root, ".norms/norms"), { recursive: true });
  writeFileSync(join(root, ".norms/config.yaml"), "version: 1\nsources:\n  - name: repository\n    path: norms\n");
  return root;
}
