import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { minimatch } from "minimatch";
import YAML from "yaml";
import authorQuality from "../../../.norms/norms/meta/author-quality.md" with { type: "text" };
import deconflictNorms from "../../../.norms/norms/meta/deconflict-norms.md" with { type: "text" };
import handleExceptions from "../../../.norms/norms/meta/handle-exceptions.md" with { type: "text" };
import inspectAssets from "../../../.norms/norms/meta/inspect-assets.md" with { type: "text" };
import normsUsage from "../../../.norms/norms/meta/norms-usage.md" with { type: "text" };
import proposeNormsSelectively from "../../../.norms/norms/meta/propose-norms-selectively.md" with { type: "text" };
import resolveScope from "../../../.norms/norms/meta/resolve-scope.md" with { type: "text" };
import respectImportOwnership from "../../../.norms/norms/meta/respect-import-ownership.md" with { type: "text" };
import verifyCompliance from "../../../.norms/norms/meta/verify-compliance.md" with { type: "text" };

export const GENERATED_MARKER = "<!-- Generated by Norms. Do not edit; run `norms sync`. -->";
export const GENERATED_ADAPTER_PATHS = [
  "AGENTS.md",
  "CLAUDE.md",
  ".cursor/rules/norms.mdc",
  ".github/copilot-instructions.md",
] as const;

export interface GeneratedAdapter {
  path: typeof GENERATED_ADAPTER_PATHS[number];
  content: string;
}

export interface SourceConfig {
  name: string;
  path?: string;
  git?: string;
  ref?: string;
}

export interface NormsConfig {
  version: 1;
  sources: SourceConfig[];
}

export interface Norm {
  id: string;
  appliesTo: string[];
  conflictsWith: string[];
  body: string;
  filePath: string;
  source: string;
}

export interface ScopeDiagnostic {
  id: string;
  source: string;
  filePath: string;
  applies: boolean;
  matchedScopes: string[];
  unmatchedScopes: string[];
  conflictsWith: string[];
}

export interface NormConflict {
  ids: [string, string];
  declaredBy: string[];
  task: string;
}

export interface ConflictReport {
  conflicts: NormConflict[];
  missingTargets: Array<{ normId: string; targetId: string }>;
}

export interface LockedSource {
  name: string;
  git: string;
  ref: string;
  commit: string;
}

export interface Lockfile {
  version: 2;
  sources: LockedSource[];
}

export interface LockfileState {
  lockfile: Lockfile;
  migratedFrom?: 1;
}

export interface StarterPack {
  version: 1;
  norms: Array<{ path: string; content: string }>;
}

export function normalizeLineEndings(value: string): string {
  return value.replace(/\r\n?/g, "\n");
}

export const STARTER_PACK: StarterPack = {
  version: 1,
  norms: ([
    ["meta/author-quality.md", authorQuality],
    ["meta/deconflict-norms.md", deconflictNorms],
    ["meta/handle-exceptions.md", handleExceptions],
    ["meta/inspect-assets.md", inspectAssets],
    ["meta/norms-usage.md", normsUsage],
    ["meta/propose-norms-selectively.md", proposeNormsSelectively],
    ["meta/resolve-scope.md", resolveScope],
    ["meta/respect-import-ownership.md", respectImportOwnership],
    ["meta/verify-compliance.md", verifyCompliance],
  ] satisfies Array<[string, string]>).map(([path, content]) => ({ path, content: normalizeLineEndings(content) })),
};

const ID_PATTERN = /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/;
const SOURCE_PATTERN = /^[a-z0-9][a-z0-9._-]*$/;

export function findRepositoryRoot(start = process.cwd()): string {
  let current = resolve(start);
  while (true) {
    if (existsSync(join(current, ".git"))) return current;
    const parent = dirname(current);
    if (parent === current) throw new Error(`No Git repository found from ${start}.`);
    current = parent;
  }
}

export function normsDirectory(root: string): string {
  return join(root, ".norms");
}

export function readConfig(root: string): NormsConfig {
  const path = join(normsDirectory(root), "config.yaml");
  if (!existsSync(path)) throw new Error("Missing .norms/config.yaml. Run `norms init`.");

  const value: unknown = YAML.parse(readFileSync(path, "utf8"));
  if (!isRecord(value) || value.version !== 1 || !Array.isArray(value.sources)) {
    throw new Error(".norms/config.yaml must contain version: 1 and a sources list.");
  }

  const sources = value.sources.map((source, index) => validateSource(source, index));
  if (sources.length === 0) throw new Error(".norms/config.yaml must define at least one source.");
  if (new Set(sources.map(({ name }) => name)).size !== sources.length) {
    throw new Error("Source names in .norms/config.yaml must be unique.");
  }
  return { version: 1, sources };
}

export function readLockfile(root: string): Lockfile {
  return readLockfileState(root).lockfile;
}

export function readStarterPack(content: string): StarterPack {
  let value: unknown;
  try {
    value = JSON.parse(content);
  } catch {
    throw new Error("Starter meta-norm cache is invalid. Reinstall Norms or remove the cache file.");
  }
  if (!isRecord(value) || value.version !== 1 || !Array.isArray(value.norms)) {
    throw new Error("Starter meta-norm cache has an unsupported format. Reinstall Norms.");
  }
  const norms = value.norms.map((norm) => {
    if (!isRecord(norm) || typeof norm.path !== "string" || typeof norm.content !== "string") {
      throw new Error("Starter meta-norm cache contains an invalid entry. Reinstall Norms.");
    }
    if (!/^meta\/[a-z0-9][a-z0-9./_-]*\.md$/.test(norm.path) || norm.path.includes("..")) {
      throw new Error(`Starter meta-norm path is invalid: ${norm.path}`);
    }
    const parsed = parseNorm(norm.content, norm.path, "starter");
    if (!parsed.id.startsWith("meta.")) throw new Error(`Starter norm ${parsed.id} must use the meta namespace.`);
    return { path: norm.path, content: normalizeLineEndings(norm.content) };
  });
  if (new Set(norms.map(({ path }) => path)).size !== norms.length) {
    throw new Error("Starter meta-norm cache contains duplicate paths. Reinstall Norms.");
  }
  return { version: 1, norms };
}

export function serializeStarterPack(pack = STARTER_PACK): string {
  const normalized = { ...pack, norms: pack.norms.map((norm) => ({ ...norm, content: normalizeLineEndings(norm.content) })) };
  return `${JSON.stringify(normalized, null, 2)}\n`;
}

export function readLockfileState(root: string): LockfileState {
  const path = join(normsDirectory(root), "lock.json");
  if (!existsSync(path)) return { lockfile: { version: 2, sources: [] } };
  let value: unknown;
  try {
    value = JSON.parse(readFileSync(path, "utf8"));
  } catch {
    throw new Error(".norms/lock.json is invalid. Restore it from Git or run `norms sync --update`.");
  }
  if (!isRecord(value) || ![1, 2].includes(value.version as number) || !Array.isArray(value.sources)) {
    throw new Error(".norms/lock.json has an unsupported format. Restore it from Git or run `norms sync --update`.");
  }
  const sources = value.sources.map((source) => {
    if (
      !isRecord(source) ||
      typeof source.name !== "string" ||
      typeof source.git !== "string" ||
      typeof source.ref !== "string" ||
      typeof source.commit !== "string" ||
      !/^[0-9a-f]{40}$/i.test(source.commit)
    ) {
      throw new Error(".norms/lock.json contains an invalid source. Restore it from Git or run `norms sync --update`.");
    }
    return { name: source.name, git: source.git, ref: source.ref, commit: source.commit };
  });
  if (new Set(sources.map(({ name }) => name)).size !== sources.length) {
    throw new Error(".norms/lock.json contains duplicate sources. Restore it from Git or run `norms sync --update`.");
  }
  return {
    lockfile: { version: 2, sources },
    migratedFrom: value.version === 1 ? 1 : undefined,
  };
}

export function resolveSourceDirectory(root: string, source: SourceConfig): string {
  const base = source.git
    ? join(normsDirectory(root), "imports", source.name)
    : normsDirectory(root);
  const defaultPath = source.git ? ".norms/norms" : "norms";
  const target = resolve(base, source.path ?? defaultPath);
  assertInside(base, target, `Source ${source.name} path`);
  return target;
}

export function loadNorms(root: string): Norm[] {
  const norms: Norm[] = [];
  for (const source of readConfig(root).sources) {
    const directory = resolveSourceDirectory(root, source);
    if (!existsSync(directory)) {
      const action = source.git ? "Run `norms sync`." : "Create it or fix .norms/config.yaml.";
      throw new Error(`Source ${source.name} is missing at ${directory}. ${action}`);
    }
    for (const filePath of markdownFiles(directory)) {
      norms.push(parseNorm(readFileSync(filePath, "utf8"), normalizeRepositoryPath(root, filePath), source.name));
    }
  }

  const seen = new Map<string, Norm>();
  for (const norm of norms) {
    const previous = seen.get(norm.id);
    if (!previous) seen.set(norm.id, norm);
    else if (
      previous.body === norm.body
      && arraysEqual(previous.appliesTo, norm.appliesTo)
      && arraysEqual(previous.conflictsWith, norm.conflictsWith)
    ) {
      previous.source = `${previous.source}, ${norm.source}`;
    } else {
      throw new Error(`Conflicting norm id ${norm.id}: ${previous.filePath} and ${norm.filePath}.`);
    }
  }
  return [...seen.values()].sort((a, b) => a.id.localeCompare(b.id));
}

export function parseNorm(markdown: string, filePath: string, source: string): Norm {
  const match = normalizeLineEndings(markdown).match(/^---\n([\s\S]*?)\n---(?:\n|$)([\s\S]*)$/);
  if (!match) throw new Error(`${filePath} must start with YAML front matter.`);

  const metadata: unknown = YAML.parse(match[1]!);
  if (!isRecord(metadata) || typeof metadata.id !== "string" || !ID_PATTERN.test(metadata.id)) {
    throw new Error(`${filePath} must define a lowercase stable id.`);
  }
  const rawScopes = metadata.applies_to ?? ["**/*"];
  const appliesTo = typeof rawScopes === "string" ? [rawScopes] : rawScopes;
  if (!Array.isArray(appliesTo) || appliesTo.some((scope) => typeof scope !== "string" || !scope)) {
    throw new Error(`${filePath} applies_to must be a string or list of strings.`);
  }
  const rawConflicts = metadata.conflicts_with ?? [];
  const conflictsWith = typeof rawConflicts === "string" ? [rawConflicts] : rawConflicts;
  if (!Array.isArray(conflictsWith) || conflictsWith.some((id) => typeof id !== "string" || !ID_PATTERN.test(id))) {
    throw new Error(`${filePath} conflicts_with must contain stable norm ids.`);
  }
  if (conflictsWith.includes(metadata.id)) throw new Error(`${filePath} cannot conflict with itself.`);
  if (new Set(conflictsWith).size !== conflictsWith.length) throw new Error(`${filePath} has duplicate conflicts_with ids.`);

  const body = match[2]!.trim();
  if (!body) throw new Error(`${filePath} must have a body.`);
  return { id: metadata.id, appliesTo: appliesTo as string[], conflictsWith: conflictsWith as string[], body, filePath, source };
}

export function serializeNorm(id: string, appliesTo: string[], body: string, conflictsWith: string[] = []): string {
  validateNormId(id);
  if (appliesTo.length === 0 || appliesTo.some((scope) => !scope)) {
    throw new Error("A norm needs at least one non-empty scope.");
  }
  for (const conflict of conflictsWith) validateNormId(conflict);
  if (conflictsWith.includes(id)) throw new Error("A norm cannot conflict with itself.");
  if (new Set(conflictsWith).size !== conflictsWith.length) throw new Error("Conflict ids must be unique.");
  const normalizedBody = normalizeLineEndings(body).trim();
  if (!normalizedBody) throw new Error("A norm body cannot be empty.");
  const metadata = YAML.stringify({ id, applies_to: appliesTo, ...(conflictsWith.length ? { conflicts_with: conflictsWith } : {}) }, { lineWidth: 0 }).trim();
  return `---\n${metadata}\n---\n\n${normalizedBody}\n`;
}

export function normPathForId(id: string): string {
  validateNormId(id);
  return `${id.replaceAll(".", "/")}.md`;
}

export function normalizeRepositoryPath(root: string, filePath: string): string {
  const value = isAbsolute(filePath) ? relative(root, filePath) : filePath;
  const normalized = value.replaceAll("\\", "/").replace(/^\.\//, "");
  if (normalized === ".." || normalized.startsWith("../")) {
    throw new Error(`${filePath} is outside the repository.`);
  }
  return normalized;
}

export function normApplies(norm: Norm, filePath: string): boolean {
  return matchingScopes(norm, filePath).length > 0;
}

export function normsForPath(norms: Norm[], filePath?: string): Norm[] {
  return filePath ? norms.filter((norm) => normApplies(norm, filePath)) : norms;
}

export function diagnoseScopes(norms: Norm[], filePath: string): ScopeDiagnostic[] {
  return norms.map((norm) => {
    const matchedScopes = matchingScopes(norm, filePath);
    return {
      id: norm.id,
      source: norm.source,
      filePath: norm.filePath,
      applies: matchedScopes.length > 0,
      matchedScopes,
      unmatchedScopes: norm.appliesTo.filter((scope) => !matchedScopes.includes(scope)),
      conflictsWith: norm.conflictsWith,
    };
  });
}

export function inspectConflicts(norms: Norm[], filePath?: string): ConflictReport {
  const byId = new Map(norms.map((norm) => [norm.id, norm]));
  const pairs = new Map<string, { ids: [string, string]; declaredBy: string[] }>();
  const missingTargets: ConflictReport["missingTargets"] = [];
  for (const norm of norms) {
    if (filePath && !normApplies(norm, filePath)) continue;
    for (const targetId of norm.conflictsWith) {
      const target = byId.get(targetId);
      if (!target) {
        missingTargets.push({ normId: norm.id, targetId });
        continue;
      }
      if (filePath && !normApplies(target, filePath)) continue;
      const ids = [norm.id, target.id].sort() as [string, string];
      const key = ids.join("\0");
      const pair = pairs.get(key) ?? { ids, declaredBy: [] };
      pair.declaredBy.push(norm.id);
      pairs.set(key, pair);
    }
  }
  const conflicts = [...pairs.values()].sort((a, b) => a.ids.join().localeCompare(b.ids.join())).map((pair) => ({
    ...pair,
    declaredBy: pair.declaredBy.sort(),
    task: `Resolve ${pair.ids[0]} and ${pair.ids[1]} into one unambiguous canonical policy. Preserve both intents where possible, explain required behavior changes, update the canonical norm files, then run \`norms sync\` and \`norms check\`.`,
  }));
  return { conflicts, missingTargets: missingTargets.sort((a, b) => `${a.normId}\0${a.targetId}`.localeCompare(`${b.normId}\0${b.targetId}`)) };
}

export function renderContext(norms: Norm[], filePath?: string): string {
  const title = filePath ? `# Active Norms for ${filePath}` : "# Active Norms";
  const sections = norms.map(
    (norm) =>
      `## ${norm.id}\n\nSource: ${norm.source}\n\nApplies to: ${norm.appliesTo.join(", ")}${norm.conflictsWith.length ? `\n\nConflicts with: ${norm.conflictsWith.join(", ")}` : ""}\n\n${norm.body}`,
  );
  return `${title}\n\n${sections.join("\n\n")}\n`;
}

export function generateAgentAdapter(norms: Norm[]): string {
  const sections = norms.map(
    (norm) =>
      `## ${norm.id}\n\nSource: \`${norm.source}\`\n\nApplies to: ${norm.appliesTo.map((scope) => `\`${scope}\``).join(", ")}${norm.conflictsWith.length ? `\n\nConflicts with: ${norm.conflictsWith.map((id) => `\`${id}\``).join(", ")}` : ""}\n\n${norm.body}`,
  );
  return normalizeLineEndings(`${GENERATED_MARKER}
# Agent Instructions

Norms are versioned instructions for agents. The active norms below are canonical for this repository.

Follow every norm whose \`applies_to\` pattern matches the files in scope. \`id\` is the norm's stable identity. \`source\` records provenance, not priority. If applicable norms conflict, report the conflict instead of choosing silently.

Do not edit this generated file. Change canonical norms in \`.norms/\`, use \`norms propose --id <id> [--scope <glob>]\` for reusable rules, and run \`norms sync\`. Use \`norms context [path] --json\` to inspect a path's norms.

# Active Norms

${sections.length ? sections.join("\n\n") : "No active norms."}
`);
}

export function generateAdapters(norms: Norm[]): GeneratedAdapter[] {
  const content = generateAgentAdapter(norms);
  return GENERATED_ADAPTER_PATHS.map((path) => ({
    path,
    content: path === ".cursor/rules/norms.mdc"
      ? `---\ndescription: Active repository norms\nglobs:\nalwaysApply: true\n---\n\n${content}`
      : content,
  }));
}

export function isGeneratedAdapter(content: string): boolean {
  if (content.startsWith(GENERATED_MARKER)) return true;
  const frontmatter = content.match(/^---\r?\n[\s\S]*?\r?\n---\r?\n\r?\n/);
  return Boolean(frontmatter && content.slice(frontmatter[0].length).startsWith(GENERATED_MARKER));
}

export function validateNormId(id: string): void {
  if (!ID_PATTERN.test(id)) {
    throw new Error("Norm ids must be lowercase words separated by '.', '-', or '_'.");
  }
}

function validateSource(value: unknown, index: number): SourceConfig {
  if (!isRecord(value) || typeof value.name !== "string" || !SOURCE_PATTERN.test(value.name)) {
    throw new Error(`Source ${index + 1} needs a lowercase name.`);
  }
  for (const key of ["path", "git", "ref"] as const) {
    if (value[key] !== undefined && typeof value[key] !== "string") {
      throw new Error(`Source ${value.name} ${key} must be a string.`);
    }
  }
  if (!value.git && value.ref) throw new Error(`Local source ${value.name} cannot define ref.`);
  return {
    name: value.name,
    path: typeof value.path === "string" ? value.path : undefined,
    git: typeof value.git === "string" ? value.git : undefined,
    ref: typeof value.ref === "string" ? value.ref : undefined,
  };
}

function markdownFiles(directory: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(directory).sort()) {
    const path = join(directory, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) files.push(...markdownFiles(path));
    else if (stat.isFile() && entry.endsWith(".md")) files.push(path);
  }
  return files;
}

function assertInside(base: string, target: string, label: string): void {
  const path = relative(resolve(base), target);
  if (path === ".." || path.startsWith(`..${sep}`) || isAbsolute(path)) {
    throw new Error(`${label} must stay inside ${base}.`);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function arraysEqual(left: string[], right: string[]): boolean {
  return left.length === right.length && left.every((value, index) => value === right[index]);
}

function matchingScopes(norm: Norm, filePath: string): string[] {
  return norm.appliesTo.filter((pattern) => minimatch(filePath, pattern, { dot: true }));
}
