import { existsSync, readFileSync, readdirSync, statSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import { minimatch } from "minimatch";
import YAML from "yaml";

export const GENERATED_MARKER = "<!-- Generated by Norms. Do not edit; run `norms sync`. -->";

export interface SourceConfig {
  name: string;
  path?: string;
  git?: string;
  ref?: string;
}

export interface NormsConfig {
  version: 1;
  sources: SourceConfig[];
}

export interface Norm {
  id: string;
  appliesTo: string[];
  body: string;
  filePath: string;
  source: string;
}

export interface LockedSource {
  name: string;
  git: string;
  ref: string;
  commit: string;
}

export interface Lockfile {
  version: 1;
  sources: LockedSource[];
}

const ID_PATTERN = /^[a-z0-9]+(?:[._-][a-z0-9]+)*$/;
const SOURCE_PATTERN = /^[a-z0-9][a-z0-9._-]*$/;

export function findRepositoryRoot(start = process.cwd()): string {
  let current = resolve(start);
  while (true) {
    if (existsSync(join(current, ".git"))) return current;
    const parent = dirname(current);
    if (parent === current) throw new Error(`No Git repository found from ${start}.`);
    current = parent;
  }
}

export function normsDirectory(root: string): string {
  return join(root, ".norms");
}

export function readConfig(root: string): NormsConfig {
  const path = join(normsDirectory(root), "config.yaml");
  if (!existsSync(path)) throw new Error("Missing .norms/config.yaml. Run `norms init`.");

  const value: unknown = YAML.parse(readFileSync(path, "utf8"));
  if (!isRecord(value) || value.version !== 1 || !Array.isArray(value.sources)) {
    throw new Error(".norms/config.yaml must contain version: 1 and a sources list.");
  }

  const sources = value.sources.map((source, index) => validateSource(source, index));
  if (sources.length === 0) throw new Error(".norms/config.yaml must define at least one source.");
  if (new Set(sources.map(({ name }) => name)).size !== sources.length) {
    throw new Error("Source names in .norms/config.yaml must be unique.");
  }
  return { version: 1, sources };
}

export function readLockfile(root: string): Lockfile {
  const path = join(normsDirectory(root), "lock.json");
  if (!existsSync(path)) return { version: 1, sources: [] };
  const value: unknown = JSON.parse(readFileSync(path, "utf8"));
  if (!isRecord(value) || value.version !== 1 || !Array.isArray(value.sources)) {
    throw new Error(".norms/lock.json is invalid. Run `norms sync`.");
  }
  const sources = value.sources.map((source) => {
    if (
      !isRecord(source) ||
      typeof source.name !== "string" ||
      typeof source.git !== "string" ||
      typeof source.ref !== "string" ||
      typeof source.commit !== "string" ||
      !/^[0-9a-f]{40}$/i.test(source.commit)
    ) {
      throw new Error(".norms/lock.json contains an invalid source. Run `norms sync`.");
    }
    return source as unknown as LockedSource;
  });
  return { version: 1, sources };
}

export function resolveSourceDirectory(root: string, source: SourceConfig): string {
  const base = source.git
    ? join(normsDirectory(root), "imports", source.name)
    : normsDirectory(root);
  const defaultPath = source.git ? ".norms/norms" : "norms";
  const target = resolve(base, source.path ?? defaultPath);
  assertInside(base, target, `Source ${source.name} path`);
  return target;
}

export function loadNorms(root: string): Norm[] {
  const norms: Norm[] = [];
  for (const source of readConfig(root).sources) {
    const directory = resolveSourceDirectory(root, source);
    if (!existsSync(directory)) {
      const action = source.git ? "Run `norms sync`." : "Create it or fix .norms/config.yaml.";
      throw new Error(`Source ${source.name} is missing at ${directory}. ${action}`);
    }
    for (const filePath of markdownFiles(directory)) {
      norms.push(parseNorm(readFileSync(filePath, "utf8"), normalizeRepositoryPath(root, filePath), source.name));
    }
  }

  const seen = new Map<string, string>();
  for (const norm of norms) {
    const previous = seen.get(norm.id);
    if (previous) throw new Error(`Duplicate norm id ${norm.id}: ${previous} and ${norm.filePath}.`);
    seen.set(norm.id, norm.filePath);
  }
  return norms.sort((a, b) => a.id.localeCompare(b.id));
}

export function parseNorm(markdown: string, filePath: string, source: string): Norm {
  const match = markdown.match(/^---\r?\n([\s\S]*?)\r?\n---(?:\r?\n|$)([\s\S]*)$/);
  if (!match) throw new Error(`${filePath} must start with YAML front matter.`);

  const metadata: unknown = YAML.parse(match[1]);
  if (!isRecord(metadata) || typeof metadata.id !== "string" || !ID_PATTERN.test(metadata.id)) {
    throw new Error(`${filePath} must define a lowercase stable id.`);
  }
  const rawScopes = metadata.applies_to ?? ["**/*"];
  const appliesTo = typeof rawScopes === "string" ? [rawScopes] : rawScopes;
  if (!Array.isArray(appliesTo) || appliesTo.some((scope) => typeof scope !== "string" || !scope)) {
    throw new Error(`${filePath} applies_to must be a string or list of strings.`);
  }

  const body = match[2].trim();
  if (!body) throw new Error(`${filePath} must have a body.`);
  return { id: metadata.id, appliesTo: appliesTo as string[], body, filePath, source };
}

export function serializeNorm(id: string, appliesTo: string[], body: string): string {
  validateNormId(id);
  if (appliesTo.length === 0 || appliesTo.some((scope) => !scope)) {
    throw new Error("A norm needs at least one non-empty scope.");
  }
  if (!body.trim()) throw new Error("A norm body cannot be empty.");
  const metadata = YAML.stringify({ id, applies_to: appliesTo }, { lineWidth: 0 }).trim();
  return `---\n${metadata}\n---\n\n${body.trim()}\n`;
}

export function normPathForId(id: string): string {
  validateNormId(id);
  return `${id.replaceAll(".", "/")}.md`;
}

export function normalizeRepositoryPath(root: string, filePath: string): string {
  const value = isAbsolute(filePath) ? relative(root, filePath) : filePath;
  const normalized = value.split(sep).join("/").replace(/^\.\//, "");
  if (normalized === ".." || normalized.startsWith("../")) {
    throw new Error(`${filePath} is outside the repository.`);
  }
  return normalized;
}

export function normApplies(norm: Norm, filePath: string): boolean {
  return norm.appliesTo.some((pattern) => minimatch(filePath, pattern, { dot: true }));
}

export function normsForPath(norms: Norm[], filePath?: string): Norm[] {
  return filePath ? norms.filter((norm) => normApplies(norm, filePath)) : norms;
}

export function renderContext(norms: Norm[], filePath?: string): string {
  const title = filePath ? `# Active Norms for ${filePath}` : "# Active Norms";
  const sections = norms.map(
    (norm) =>
      `## ${norm.id}\n\nSource: ${norm.source}\n\nApplies to: ${norm.appliesTo.join(", ")}\n\n${norm.body}`,
  );
  return `${title}\n\n${sections.join("\n\n")}\n`;
}

export function generateAgentAdapter(norms: Norm[]): string {
  const sections = norms.map(
    (norm) =>
      `## ${norm.id}\n\nSource: \`${norm.source}\`\n\nApplies to: ${norm.appliesTo.map((scope) => `\`${scope}\``).join(", ")}\n\n${norm.body}`,
  );
  return `${GENERATED_MARKER}
# Agent Instructions

Norms are versioned instructions for agents. The active norms below are canonical for this repository.

Follow every norm whose \`applies_to\` pattern matches the files in scope. \`id\` is the norm's stable identity. \`source\` records provenance, not priority. If applicable norms conflict, report the conflict instead of choosing silently.

Do not edit this generated file. Change canonical norms in \`.norms/\`, use \`norms propose --id <id> [--scope <glob>]\` for reusable rules, and run \`norms sync\`. Use \`norms context [path] --json\` to inspect a path's norms.

# Active Norms

${sections.length ? sections.join("\n\n") : "No active norms."}
`;
}

export function isGeneratedAdapter(content: string): boolean {
  return content.startsWith(GENERATED_MARKER);
}

export function validateNormId(id: string): void {
  if (!ID_PATTERN.test(id)) {
    throw new Error("Norm ids must be lowercase words separated by '.', '-', or '_'.");
  }
}

function validateSource(value: unknown, index: number): SourceConfig {
  if (!isRecord(value) || typeof value.name !== "string" || !SOURCE_PATTERN.test(value.name)) {
    throw new Error(`Source ${index + 1} needs a lowercase name.`);
  }
  for (const key of ["path", "git", "ref"] as const) {
    if (value[key] !== undefined && typeof value[key] !== "string") {
      throw new Error(`Source ${value.name} ${key} must be a string.`);
    }
  }
  if (!value.git && value.ref) throw new Error(`Local source ${value.name} cannot define ref.`);
  return {
    name: value.name,
    path: typeof value.path === "string" ? value.path : undefined,
    git: typeof value.git === "string" ? value.git : undefined,
    ref: typeof value.ref === "string" ? value.ref : undefined,
  };
}

function markdownFiles(directory: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(directory).sort()) {
    const path = join(directory, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) files.push(...markdownFiles(path));
    else if (stat.isFile() && entry.endsWith(".md")) files.push(path);
  }
  return files;
}

function assertInside(base: string, target: string, label: string): void {
  const path = relative(resolve(base), target);
  if (path === ".." || path.startsWith(`..${sep}`) || isAbsolute(path)) {
    throw new Error(`${label} must stay inside ${base}.`);
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
